name: CI for Submit and Pull Request

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 16
          cache: "gradle"

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --no-daemon

      - name: Upload build result
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/libs
